import React from "react";
import ReactDOM from "react-dom";
import App from "./App";
import Roadmap from "./Roadmap";
import "./index.css";
import Navbar from "./Navbar";
import Login_Form from "./Login_Form";
ReactDOM.render(<Navbar />, document.getElementById("root2"));
ReactDOM.render(<Roadmap />, document.getElementById("root"));
ReactDOM.render(<Login_Form />, document.getElementById("root3"));
