post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aXRsZSI6InRlc3RibG9nIiwiYXV0aG9yIjoiU3RyaW5nIiwidXJsIjoiU3RyaW5nIiwibGlrZXMiOjMsInVzZXJJZCI6IjVkYTM0OTdjOTI0M2U2Mzk4YzNjZjU4OSJ9.o9MQgkCnNS3jMhMYAxnLq6RrJBRxtajTR-vU3A9Mcy8

{
"title": "blog2", 
"author": "john stein beck",
 "url":"N/A", 
 "likes": 3432, 
 "userId":"5da4e601d7bf44404867556f"
}

//make sure the set up looks exactly like this with extra lines
//the token must be different for each note
//so put this object in the payload data for 
//https://jwt.io/ 
//it will generate a token and then it will output the bearer
//place the bearer token in the authorization header 