post http://localhost:3003/api/users
Content-Type: application/json

{
"username": "testfing", 
"password": "hsdfa"
}


# const blogSchema = mongoose.Schema({
#   title: String,
#   author: String,
#   url: String,
#   likes: Number
# });